#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

use function Differ\Differ\genDiff;

$options = getopt('', ['format:']);
$args = array_values(array_diff($argv, ['--format', $options['format'] ?? null]));

$path1 = $args[1] ?? null;
$path2 = $args[2] ?? null;
$format = $options['format'] ?? 'stylish';

if (!$path1 || !$path2) {
    fwrite(STDERR, "Usage: gendiff [--format FORMAT] file1 file2\n");
    exit(1);
}

echo genDiff($path1, $path2, $format) . PHP_EOL;